name: Build portfolio

# Trigger
on: 
  push:
    branches: 
      - deployment
  
jobs: 
  deployment: 
    name: publish docker images 
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.USER}}
          passwword: ${{secrets.DOCKER_PAT}}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with: 
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tag: cyrof/kn-folio

