name: Lint

on: 
  pull_request:

jobs:
  lint:
    runs_on: ubuntu-24.04
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@4
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint