name: Release & publish Docker on stable 

on: 
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}

    steps:
      - name: Checkout full history
        uses: actions/checkout@v
        with: 
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Get version
        id: get_version
        run: |
          VER=$(jq -r .version package.json)}
          echo "::set-output name=tag::v$VER"
    
      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@user.noreply.github.com"
          git tag ${{ steps.get_version.outputs.tag }}
          git push origin ${{ steps.get_version.output.tag }}
        env:
          GITHUB_TOKEN: ${{ secret.GH_PAT }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          release_name: Release ${{ steps.get_version.output.tag }}
          body: |
            Automated release for ${{ steps.get_version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secret.GH_PAT }}
  
  docker:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Builx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USER}}
          password: ${{secrets.DOCKER_PAT}}
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            cyrof/kn-folio:${{ needs.release.outputs.tag }}
            cyrof/kn-folio:latest
